{
 "title": "OCA Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "oca",
    "label": "OCA App: ",
    "query": {
     "query": "query_result(sum by (label)(deployment_active{label=~\".*\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Deployment Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (id,label,image,deployment_total)(deployment_active))"
    }
   ]
  },
  {
   "title": "Total Deployment Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (label)(deployment_total))"
    }
   ]
  },
  {
   "title": "OCA Trend",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (label)(deployment_active{label=\"$oca\"})"
    }
   ]
  },
  {
   "title": "Distro Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (image)(deployment_active))"
    }
   ]
  },
  {
   "title": "OCA Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(deployment_active)" }
   ]
  }
 ]
}